/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'raquel' at '10/3/16 8:49 PM' with Gradle 2.13
 *
 * @author raquel, @date 10/3/16 8:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
